import "unknwn.idl";
//MyMath Interface 
//Interface definition block 
//1. attribute block 
[
	object,
	uuid(6641FCB9-5D50-429E-9967-AAD944C0F5BD), //from Automation Server.h -> IID_MyMath
	helpstring("This is IMyMath Interface decleration"), //Tools -> oleComViewer
	pointer_default(unique),
	dual,//
	oleautomation//oleautomation
]
//2. decleration block
interface IMyMath : IDispatch 
{
	import "oaidl.idl";// oa : OLE automation
	HRESULT __stdcall SumOfTwoIntegers([in] int, [in] int, [out,retval]int*);
	HRESULT __stdcall SubtractionOfTwoIntegers([in] int,[in] int,[out,retval] int*);
};

//Type library definition block
//1.attribute block
[
	uuid(EA3D3E04-2F1B-4E54-8E8A-871BE06D067B),
	version(1.0),//major version number. minor version number -> LoadRegTypeLib 2nd and 3rd parameter
	helpstring("This is automation server Type Libaray")
]
//2.decleration block
library AutomationServerTypeLib
{
	importlib("stdole32.tlb");
	//component code
	//Coclass definition block
	//1.attribute block of Coclass definition block
	[
		uuid(94248ECA-86B3-4A90-9DAB-E969BE8B62A8), //CLSID of MyMath component
		helpstring("MyMath Component's type libarary")
	]
	//2.decleration block of Coclass definition block 
	coclass CMyMath
	{
		[default] interface IMyMath;
	};
};
